# Generated by Django 6.0.6 on 2026-06-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calorie_Counter_app', '0002_infomodel_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infomodel',
            name='profile_image',
            field=models.ImageField(blank=True, max_length=50, null=True, upload_to='profile_image/'),
        ),
    ]
